# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfccd191f7751cbf18c809fb90b5740f13291585f3cc48e23bb3b3a66c50e88bc0b632aa4a044d8ed9feb5563fcd154932d10c6be05af53c15d6679439b5c31c

test:
  secret_key_base: e36fd096157eeb60d46eb7510380ab469b34eca3205db5429eb968695282e66aea9347aae793a732cc2d152a8e309e8b93c5c4932ff200e2744fbf0c535fc179

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
